name: PR Deploy (Preview)

on:
  workflow_call:

env:
  CLOUDFLARE_PROJECT_NAME: landingpage
  CLOUDFLARE_BRANCH_NAME: '#${{ github.event.pull_request.number }} / ${{ github.event.pull_request.title }}'
  HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}
  HEAD_REF: ${{ github.event.pull_request.head.ref }}

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          repository: ${{ env.HEAD_REPO }}
          ref: ${{ env.HEAD_REF }}
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: pages deploy dist --project-name="${{ env.CLOUDFLARE_PROJECT_NAME }}" --branch="${{ env.CLOUDFLARE_BRANCH_NAME }}"
      - name: Update Preview Link Comment
        env:
          PREVIEW_LINK: ${{ steps.deploy.outputs.deployment-url }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          comment_tag: cloudflare_preview_message
          message: |
            **PR Preview**
            |                Name                 |                  Preview                 |
            | ----------------------------------- | ---------------------------------------- |
            | ${{ env.CLOUDFLARE_BRANCH_NAME }} | [Visit Preview](${{ env.PREVIEW_LINK }}) |
