name: PR Semantics
on:
  workflow_call:


jobs:
  main:
    name: Validate PR Title Semantics
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    
